name: my_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.4
  flutter_lints: ^5.0.0
  analyzer: ^5.8.0
  build_runner_core: ^7.3.2

flutter:
  uses-material-design: true
